name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *" # run daily
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Activity & Achievements Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          config_timezone: Asia/Kolkata
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
