name: Update GitHub Profile Stats
on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: thecodekaizen
          BRANCH_NAME: main
          UTC_OFFSET: 5.5
          THEME: github_dark
